### ISSUE TITLE
Possiblity of having glare always on, even without hovering

### ISSUE THREAD

**Issue by BartekSadurski** [rashidshamloo/react-next-parallax#1]

**Comment by rashidshamloo** [comment]
Can you explain more about what you mean and its use case?

Do you want to control the glare elements in the code separately without tilting the component itself?

Or do you want to set a default (rest) position/opacity for the glare elements?

**Comment by BartekSadurski** [comment]
@rashidshamloo What I mean is basically having the glare effect always on, in a static preset position.
So even if I start hovering over the element, the glare effect will still stay there visible.
![example](https://i.imgur.com/Kl6Gacv.png)

^ Basically look like this even without tilting the card.

**Comment by rashidshamloo** [comment]
Thanks for the explanation.

I have added the `lineGlareFixedPosition` and `spotGlareFixedPosition` properties which can be used to set a fixed position for the glare elements.

You can supply preset positions like "top-left", "center", etc. as well as precise positions by providing an object containing the `left` property for the line glare element. and `left` and `top` properties for the spot glare element.

example: 
```spotGlareFixedPosition="top-left"```
```spotGlareFixedPosition={{ left: '20%', top: '50px' }}``` 

`left` and `top` properties can be set to percentage as well as pixel values.

These properties can also be used to animate the glare elements inside the code without affecting or being affected by the tilt angle.

You can play around with them (the presets) in the Storybook:

- [Line Glare](https://rashidshamloo.github.io/react-next-tilt/?path=/story/tilt-react-next-tilt--line-glare)
- [Spot Glare](https://rashidshamloo.github.io/react-next-tilt/?path=/story/tilt-react-next-tilt--spot-glare)

Please let me know if this works for your use case.
